### ISSUE TITLE
Can someone update the SDK to 5.2.0

### ISSUE THREAD

**Issue by eyalish** [Heyzap/heyzap-cordova-facebook_audience_network#1]
We get no fills of impressions because the SDK here is ancient
Facebook Support says I need to update the SDK
Anyone from Heyzap or Fyber can update the plugin.

**Comment by ekilah** [comment]
I no longer work for the company, sorry. Please reach out to their support team.

**Comment by MaxGabriel** [comment]
I also no longer work for the company. But fwiw, it's probably possible to do the upgrade to 5.2.0 yourself if you want to give that a shot
